### ISSUE TITLE
Add new Tokens

### ISSUE THREAD

**Issue by wellintj** [OasisDEX/eth2dai#244]
This project is really amazing.

I'd like to know how to add new tokens.  I took a look in the file  src\blockchain\config But I couldn't understand it well.  Thanks a lot.

**Comment by peculiarity** [comment]
@wellintj  Hello and welcome! Glad to have you here.

Apologies for the late response but we've been quite busy with adding new features.

I would suggest you to follow the same pattern and add your token of choice in the `tokens` map. If you don't have an icon you can simply reuse the ethereum one. Some of the properties there as you can see are just for formatting. I advise you to use the values that are used for other tokens. It's important to know in advance the precision the token you are trying to use. You have to put the correct number since you might see incorrect numbers ( again formatting related ).

After that initial configuration you have to add the address of the token for `main` and `kovan` networks. It's under the `getter` for each of the networks.

If you have any issues with the configuration or any other questions, feel free to ask!
