### ISSUE TITLE
"unlocking" WETH tries to do something with an unbelievably large number of WETH

### ISSUE THREAD

**Issue by mediocregopher** [OasisDEX/eth2dai#294]
I'm not actually sure what "unlocking" does, except that the frontend tells me I must do it in order to trade. I have 0.5 WETH in my metamask wallet, and when I hit the "unlock" toggle I get a popup that looks like this:

![shot](https://user-images.githubusercontent.com/933154/63654963-10c93680-c73f-11e9-82e8-9be0fbf3bbe2.png)
![shot](https://user-images.githubusercontent.com/933154/63654965-1de62580-c73f-11e9-9782-3bb49e0c59c4.png)

Not totally sure where to go from here, am happy to provide any other debug info you need.

**Comment by peculiarity** [comment]
hey @mediocregopher . Glad to have you on board.
Locking/Unlocking is basically giving approval of the OTC smart contract to execute trades on your behalf. If you checkout the internal logic of the smart contract you will gain more insight how things work.

The big number that you see comes from the value that is provided to the approve method. The value is the biggest possible value. This is the way in which "binary" switch for approval is simulated. It simply means that you don't have to worry about the amount you granted the contract to use on your behalf ever again since the number is reeeeallly big.

If you continue with the transaction you will see that you will be charged only the gas fee and nothing else.

Feel free to ask more question!
